import type { World } from '../World';
import { ZONE_R, ZONE_C, ZONE_I, ZONE_NONE } from '../constants';
import { BALANCE } from '../../data/balance';

/**
 * CrimeSystem calculates crime levels per tile.
 * Crime is generated by developed zones, scaled by their level.
 * Police coverage significantly reduces crime.
 * Crime values are smoothed over time to prevent flickering and represent steady-state.
 */
export class CrimeSystem {
  private _lastAlertTick = -Infinity;

  update(world: World): void {
    const { width, height } = world.grid;
    const n = width * height;
    const zone = world.layers.zone;
    const dev = world.layers.devLevel;
    const police = world.layers.police;
    const crime = world.layers.crime;
    const b = BALANCE.crime;

    for (let i = 0; i < n; i++) {
      const z = zone[i];
      if (z === ZONE_NONE) {
        // No zone, crime decays to 0.
        crime[i] = Math.floor(crime[i] * (1 - b.smoothing));
        continue;
      }

      const level = dev[i];
      if (level === 0) {
        // Undeveloped zone, minimal crime or decay.
        crime[i] = Math.floor(crime[i] * (1 - b.smoothing));
        continue;
      }

      // Calculate target crime for this tile based on zone type and level.
      let baseRate = 0;
      if (z === ZONE_R) baseRate = b.baseRateR;
      else if (z === ZONE_C) baseRate = b.baseRateC;
      else if (z === ZONE_I) baseRate = b.baseRateI;

      let targetCrime = baseRate * level * 40; // Increased from 20 to 40

      // Police reduction.
      if (police[i] === 1) {
        targetCrime *= b.policeEffectiveness;
      }

      // Education reduction for R zones.
      if (z === ZONE_R) {
        const edu = world.layers.education[i];
        // 0 education = 1.0 mult, 255 education = BALANCE.education.crimeReduction
        const eduMult = 1.0 - (edu / 255) * (1.0 - BALANCE.education.crimeReduction);
        targetCrime *= eduMult;
      }

      // Clamp target.
      targetCrime = Math.min(255, Math.max(0, targetCrime));

      // Smooth current value toward target.
      const current = crime[i];
      const next = current + (targetCrime - current) * b.smoothing;
      let rounded = Math.round(next);
      // Nudge if we are stuck but far from target.
      if (rounded === current && Math.abs(targetCrime - current) >= 0.5) {
        rounded += Math.sign(targetCrime - current);
      }
      crime[i] = Math.min(255, Math.max(0, rounded));
    }

    // Emit crimeSpike when city-wide average exceeds threshold (with cooldown).
    const cooldown = world.tick - this._lastAlertTick >= b.alertCooldownTicks;
    if (cooldown) {
      let crimeSum = 0;
      let crimeCount = 0;
      let affectedTiles = 0;
      for (let i = 0; i < n; i++) {
        if (zone[i] !== ZONE_NONE && dev[i] > 0) {
          crimeSum += crime[i];
          crimeCount++;
          if (crime[i] > b.alertThreshold) affectedTiles++;
        }
      }
      const avgCrime = crimeCount > 0 ? crimeSum / crimeCount : 0;
      if (avgCrime > b.alertThreshold) {
        world.events.emit('crimeSpike', { avgCrime, threshold: b.alertThreshold, affectedTiles });
        this._lastAlertTick = world.tick;
      }
    }
  }
}
